### ISSUE TITLE
Conditional tab items

### ISSUE THREAD

**Issue by ajmeese7** [os-js/osjs-settings-application#11]
Hey again, question about implementing some behavior that I have been struggling with for a couple hours.

For context, in my implementation of OS.js I am adding in dynamic wallpapers. On the `Background` tab in the Settings menu, I have a dropdown that allows the user to switch between the normal static wallpaper or a dynamic wallpaper. Each dynamic wallpaper will have its own options, such as different colors, speeds, and modes. What I would like to do is have the settings beneath the dropdown change based on whether the user has `Static` or `Dynamic` chosen in the `Select` dropdown, but I can't get the window to update the displayed elements even when the state changes becaue the user switches their selected option.

How would I go about having the `items` array display different options conditionally based upon the state of one of its components?

**Comment by andersevenrud** [comment]
Something like this ?

https://codepen.io/andersevenrud/pen/dyJyaog

You'll have to use the state in order to achieve this with some basic events.

**Comment by ajmeese7** [comment]
Sorry for the confusing explanation, I meant conditional settings items within a tab. Something like the following:

![standard settings](https://user-images.githubusercontent.com/17814535/158241809-af4c2191-1963-4a4d-9112-fd38a610120c.png)

![dynamic settings](https://user-images.githubusercontent.com/17814535/158242581-58bb0f62-a719-434e-a47f-3472deff96cb.png)

**Comment by andersevenrud** [comment]
Ah.

> within a tab

A "tab" is just a container, so anything I write here could be used anywhere, FYI.

So like this then ?

https://codepen.io/andersevenrud/pen/popvOYv

**Comment by ajmeese7** [comment]
Exactly like that! You're the best, thanks a million
