### ISSUE TITLE
Need an option to change font color of desktop icons

### ISSUE THREAD

**Issue by valp124** [os-js/osjs-settings-application#7]
I happen to have a dark bg image for my desktop, and the icons look like this:

![image](https://user-images.githubusercontent.com/7969539/77113388-2070db00-6a01-11ea-90b3-3800f1e229ba.png)

It'd be awesome if there was a setting for the font color!

**Comment by andersevenrud** [comment]
Indeed. This was a feature in v2. There actually was a setting to use an inverted version of the background color so that the contrast would be OK in most cases.

**Comment by andersevenrud** [comment]
I've opened a PR for this in osjs-client adds this functionality: https://github.com/os-js/osjs-client/pull/105

Next up is UI in this application :blush:

**Comment by andersevenrud** [comment]
And here's the UI updates for settings application: https://github.com/os-js/osjs-settings-application/pull/8

If you want to test this, just do the same with osjs-client as last time. As for this application, almost same deal, just place it in `src/packages` and run `npm run build` as well inside the package. As long as you have latest osjs-cli, this package should get prioritized above the one from npm when you run `npm run package:discover`.

**Comment by andersevenrud** [comment]
![OS js](https://user-images.githubusercontent.com/161548/77117900-3e573380-6a33-11ea-9da4-7e070070c176.png)

**Comment by valp124** [comment]
What a genius you are, man! For testing, I'll defer this to @josephjeno, my local build genius 😄

**Comment by josephjeno** [comment]
I can select a custom color, however the background text remains the same, even after refreshing the page. I'm using Google Chrome.

![image](https://user-images.githubusercontent.com/29079278/77131215-39918000-6a31-11ea-98d3-003304c2748f.png)

Do I need to enable something in the client config maybe?

```
  // Desktop Settings
  desktop: {
    lock: true,
    contextmenu: false,
    settings: {
      background: {
        //src: require('./wallpaper.png'),
        color: '#572a79'
      },
      iconview: {
        enabled: true,
        path: 'home:/.desktop'
      }
    }
  },
```

**Comment by andersevenrud** [comment]
No need to change anything.

1. Are you using a local osjs-client ?
2. Is this used as the import in your bootstrap ?
3. Did you check out the correct branch ? (see PR)
4. If you're using the osjs-client from last time you tested, make sure to run `git fetch` before checking out the branch

**Comment by josephjeno** [comment]
Ah thanks, I missed the part about also changing osjs-client. New text colors look great!

![image](https://user-images.githubusercontent.com/29079278/77233341-48854900-6b7d-11ea-9afd-f6a1c4c7bd16.png)

**Comment by andersevenrud** [comment]
Awesome! :)

I've published a new version of osjs-client and osjs-settings-application.

With the new osjs-client I've also made some style adjustments that will fix letters like the cut off "g" you see there.
